import { Provider } from 'react-redux';
import './globals.css';
import { Inter } from 'next/font/google';
import { ReduxProvider } from '@/redux/provider';
import Navbar from '@/components/navbar/pages';

const inter = Inter({ subsets: ['latin'] });

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ReduxProvider>
          <Navbar />
          {children}
        </ReduxProvider>
      </body>
    </html>
  );
}
